module(
    name = "lucid",
    version = "0.1",
)

bazel_dep(name = "rules_cc", version = "0.2.17")

bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)
bazel_dep(name = "google_benchmark", version = "1.9.5", dev_dependency = True)
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
bazel_dep(name = "platforms", version = "1.0.0", dev_dependency = True)

git_override(
    module_name = "hedron_compile_commands",
    commit = "d7d9efd0e2315fccd03e413796a3267ba001b732",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
)
