load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "cfg",
    hdrs = ["cfg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
        "//lucid/core/container:arena",
        "//lucid/core/container:hash_set",
    ],
)

cc_library(
    name = "cfg_printer",
    srcs = ["cfg_printer.cc"],
    hdrs = ["cfg_printer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":instructions",
    ],
)

cc_library(
    name = "instructions",
    hdrs = ["instructions.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "instructions_test",
    srcs = ["instructions_test.cc"],
    deps = [
        ":instructions",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "liveness",
    srcs = ["liveness.cc"],
    hdrs = ["liveness.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        "//lucid/core/container:hash_set",
    ],
)

cc_test(
    name = "liveness_test",
    srcs = ["liveness_test.cc"],
    deps = [
        ":cfg",
        ":instructions",
        ":liveness",
        "//lucid/core/dataflow",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
        "//lucid/syntax:lexer",
        "@googletest//:gtest_main",
    ],
)
