load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "cfg",
    hdrs = ["cfg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
        "//lucid/core/container:arena",
    ],
)

cc_library(
    name = "cfg_builder",
    testonly = True,
    hdrs = ["cfg_builder.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
    ],
)

cc_library(
    name = "cfg_printer",
    srcs = ["cfg_printer.cc"],
    hdrs = ["cfg_printer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":instructions",
        "//lucid/core/cli:format",
    ],
)

cc_library(
    name = "ig",
    srcs = ["ig.cc"],
    hdrs = ["ig.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":liveness",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/container/graph:dominator",
        "//lucid/core/dataflow",
    ],
)

cc_test(
    name = "ig_test",
    srcs = ["ig_test.cc"],
    deps = [
        ":cfg",
        ":cfg_builder",
        ":ig",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "instructions",
    hdrs = ["instructions.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/hash",
    ],
)

cc_test(
    name = "instructions_test",
    srcs = ["instructions_test.cc"],
    deps = [
        ":instructions",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "liveness",
    srcs = ["liveness.cc"],
    hdrs = ["liveness.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        "//lucid/core/container:hash_set",
    ],
)

cc_test(
    name = "liveness_test",
    srcs = ["liveness_test.cc"],
    deps = [
        ":cfg",
        ":cfg_builder",
        ":instructions",
        ":liveness",
        "//lucid/core/dataflow",
        "//lucid/core/string:index",
        "//lucid/core/testing",
        "//lucid/syntax:ast",
        "//lucid/syntax:lexer",
    ],
)

cc_library(
    name = "opt",
    srcs = ["opt.cc"],
    hdrs = ["opt.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
    ],
)

cc_test(
    name = "opt_test",
    srcs = ["opt_test.cc"],
    deps = [
        ":instructions",
        ":opt",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "reg",
    srcs = ["reg.cc"],
    hdrs = ["reg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":cfg_printer",
        ":liveness",
        ":state",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/dataflow",
    ],
)

cc_test(
    name = "reg_test",
    srcs = ["reg_test.cc"],
    deps = [
        ":cfg",
        ":ig",
        ":instructions",
        ":opt",
        ":reg",
        ":translator",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/testing",
        "//lucid/syntax:ast",
        "//lucid/syntax:cfg",
        "//lucid/syntax:comp",
        "//lucid/syntax:lexer",
        "//lucid/syntax:parser",
        "//lucid/syntax:ssa",
        "//lucid/syntax:type",
    ],
)

cc_binary(
    name = "reg_bench",
    srcs = ["reg_bench.cc"],
    deps = [
        ":cfg",
        ":ig",
        ":instructions",
        ":opt",
        ":reg",
        ":state",
        ":translator",
        "//lucid/core/benchmarking",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/syntax:ast",
        "//lucid/syntax:cfg",
        "//lucid/syntax:comp",
        "//lucid/syntax:lexer",
        "//lucid/syntax:parser",
        "//lucid/syntax:ssa",
        "//lucid/syntax:type",
    ],
)

cc_library(
    name = "state",
    hdrs = ["state.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
        "//lucid/core/container:hash_set",
        "//lucid/core/string:index",
    ],
)

cc_library(
    name = "translator",
    srcs = ["translator.cc"],
    hdrs = ["translator.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":instructions",
        ":state",
        "//lucid/core/container:arena",
        "//lucid/core/container:hash_map",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
        "//lucid/syntax:cfg",
        "//lucid/vm:interpreter",
    ],
)

cc_test(
    name = "translator_test",
    srcs = ["translator_test.cc"],
    deps = [
        ":instructions",
        ":translator",
        "//lucid/core/container/graph:order",
        "//lucid/core/testing",
        "//lucid/syntax:ast_fixture",
        "//lucid/syntax:cfg",
        "//lucid/syntax:type",
    ],
)

cc_binary(
    name = "translator_bench",
    srcs = ["translator_bench.cc"],
    deps = [
        ":translator",
        "//lucid/core/benchmarking",
        "//lucid/syntax:cfg",
        "//lucid/syntax:comp",
        "//lucid/syntax:lexer",
        "//lucid/syntax:parser",
        "//lucid/syntax:ssa",
        "//lucid/syntax:type",
    ],
)
