load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "cfg",
    hdrs = ["cfg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
        "//lucid/core/container:arena",
        "//lucid/core/container:hash_set",
    ],
)

cc_library(
    name = "cfg_printer",
    srcs = ["cfg_printer.cc"],
    hdrs = ["cfg_printer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":instructions",
    ],
)

cc_library(
    name = "instructions",
    hdrs = ["instructions.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "instructions_test",
    srcs = ["instructions_test.cc"],
    deps = [
        ":instructions",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "liveness",
    srcs = ["liveness.cc"],
    hdrs = ["liveness.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        "//lucid/core/container:hash_set",
    ],
)

cc_test(
    name = "liveness_test",
    srcs = ["liveness_test.cc"],
    deps = [
        ":cfg",
        ":instructions",
        ":liveness",
        "//lucid/core/dataflow",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
        "//lucid/syntax:lexer",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "opt",
    srcs = ["opt.cc"],
    hdrs = ["opt.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":instructions",
    ],
)

cc_test(
    name = "opt_test",
    srcs = ["opt_test.cc"],
    deps = [
        ":instructions",
        ":opt",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "reg",
    srcs = ["reg.cc"],
    hdrs = ["reg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":liveness",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/container/graph:dominator",
        "//lucid/core/dataflow",
    ],
)

cc_test(
    name = "reg_test",
    srcs = ["reg_test.cc"],
    deps = [
        ":cfg",
        ":reg",
        "//lucid/syntax:ast",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "translator",
    srcs = ["translator.cc"],
    hdrs = ["translator.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":cfg",
        ":instructions",
        "//lucid/core/container:arena",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
        "//lucid/syntax:cfg",
    ],
)

cc_test(
    name = "translator_test",
    srcs = ["translator_test.cc"],
    deps = [
        ":instructions",
        ":translator",
        "//lucid:type",
        "//lucid/core/container/graph:order",
        "//lucid/syntax:ast_fixture",
        "//lucid/syntax:cfg",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "translator_bench",
    srcs = ["translator_bench.cc"],
    deps = [
        ":translator",
        "//lucid/syntax:cfg",
        "//lucid/syntax:lexer",
        "//lucid/syntax:parser",
        "@google_benchmark//:benchmark",
    ],
)
