load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "ast",
    hdrs = ["ast.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/container:arena",
        "//lucid/core/container:successive_list",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "ast_test",
    srcs = ["ast_test.cc"],
    deps = [
        ":ast",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "ast_fixture",
    testonly = True,
    hdrs = ["ast_fixture.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        "//lucid/core/container:arena",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:successive_list",
        "//lucid/core/string:index",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "ast_printer",
    srcs = ["ast_printer.cc"],
    hdrs = ["ast_printer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        "//lucid/core/cli:format",
    ],
)

cc_library(
    name = "buffered_lexer",
    srcs = ["buffered_lexer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":token",
    ],
)

cc_test(
    name = "buffered_lexer_test",
    srcs = ["buffered_lexer_test.cc"],
    deps = [
        ":buffered_lexer",
        ":lexer",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "cfg",
    srcs = ["cfg.cc"],
    hdrs = ["cfg.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        "//lucid/core/container:arena",
        "//lucid/core/container:successive_list",
    ],
)

cc_test(
    name = "cfg_test",
    srcs = ["cfg_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":cfg",
        "//lucid/core/container:arena",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "cfg_printer",
    srcs = ["cfg_printer.cc"],
    hdrs = ["cfg_printer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":cfg",
        ":context",
        "//lucid/core/cli:format",
    ],
)

cc_library(
    name = "comp",
    srcs = ["comp.cc"],
    hdrs = ["comp.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "comp_test",
    srcs = ["comp_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":comp",
        ":lexer",
        ":parser",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "context",
    hdrs = ["context.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":type_repository",
        "//lucid/core/container:arena",
        "//lucid/core/string:index",
    ],
)

cc_library(
    name = "lexer",
    hdrs = ["lexer.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":token",
    ],
)

cc_test(
    name = "lexer_test",
    srcs = ["lexer_test.cc"],
    deps = [
        ":lexer",
        ":token",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "lexer_bench",
    srcs = ["lexer_bench.cc"],
    data = [
        "//examples:example_sources",
    ],
    deps = [
        ":lexer",
        ":token",
        "//lucid/core/benchmarking",
        "//lucid/core/io:file",
    ],
)

cc_library(
    name = "liveness",
    srcs = ["liveness.cc"],
    hdrs = ["liveness.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":cfg",
        ":context",
        "//lucid/core/container:hash_set",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "liveness_test",
    srcs = ["liveness_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":cfg",
        ":liveness",
        "//lucid/core/dataflow",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "parser",
    hdrs = ["parser.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        ":lexer",
        ":token",
        "//lucid/core/container:arena",
        "//lucid/core/container:fixed_map",
        "//lucid/core/container:successive_list",
        "//lucid/core/functional:expected",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "parser_test",
    srcs = ["parser_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":lexer",
        ":parser",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "parser_bench",
    srcs = ["parser_bench.cc"],
    data = [
        "//examples:example_sources",
    ],
    deps = [
        ":buffered_lexer",
        ":lexer",
        ":parser",
        ":token",
        "//lucid/core/benchmarking",
        "//lucid/core/io:file",
    ],
)

cc_library(
    name = "ssa",
    srcs = ["ssa.cc"],
    hdrs = ["ssa.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":cfg",
        ":context",
        ":liveness",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/container/graph:dominator",
        "//lucid/core/dataflow",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "ssa_test",
    srcs = ["ssa_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":cfg",
        ":ssa",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "ssa_bench",
    srcs = ["ssa_bench.cc"],
    deps = [
        ":ast",
        ":cfg",
        ":comp",
        ":context",
        ":lexer",
        ":parser",
        ":ssa",
        ":type",
        "//lucid/core/benchmarking",
    ],
)

cc_library(
    name = "token",
    srcs = ["token.cc"],
    hdrs = ["token.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "token_test",
    srcs = ["token_test.cc"],
    deps = [
        ":token",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "type",
    srcs = ["type.cc"],
    hdrs = ["type.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":ast",
        ":context",
        "//lucid/core/container:hash_map",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "type_test",
    srcs = ["type_test.cc"],
    deps = [
        ":ast",
        ":ast_fixture",
        ":type",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "type_repository",
    srcs = ["type_repository.cc"],
    hdrs = ["type_repository.h"],
    deps = [
        ":ast",
        "//lucid/core/container:arena",
        "//lucid/core/container:hash_map",
        "//lucid/core/string:index",
    ],
)

cc_test(
    name = "type_repository_test",
    srcs = ["type_repository_test.cc"],
    deps = [
        ":type_repository",
        "//lucid/core/string:index",
        "//lucid/core/testing",
    ],
)
