load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "token",
    srcs = ["token.cc"],
    hdrs = ["token.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "token_test",
    srcs = ["token_test.cc"],
    deps = [
        ":token",
        "@googletest//:gtest_main",
    ],
)
