load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "hash",
    hdrs = ["hash.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "hash_test",
    srcs = ["hash_test.cc"],
    deps = [
        ":hash",
        "//lucid/core/testing",
    ],
)
