load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "assembler",
    hdrs = ["assembler.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/container:hash_map",
        "//lucid/core/numeric:bits",
        "//lucid/core/string:encoding",
    ],
)

cc_test(
    name = "assembler_test",
    srcs = ["assembler_test.cc"],
    deps = [
        ":assembler",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "macho",
    srcs = ["macho.cc"],
    hdrs = ["macho.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":assembler",
    ],
)

cc_library(
    name = "translator",
    srcs = ["translator.cc"],
    hdrs = ["translator.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":assembler",
        "//lucid/am:cfg",
        "//lucid/am:instructions",
        "//lucid/am:state",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/container/graph:order",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
        "//lucid/syntax:context",
    ],
)

cc_test(
    name = "translator_test",
    srcs = ["translator_test.cc"],
    deps = [
        ":translator",
        "@googletest//:gtest_main",
    ],
)
