load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "dataflow",
    hdrs = ["dataflow.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":worklist",
        "//lucid/core/container:hash_map",
        "//lucid/core/container/graph",
        "//lucid/core/container/graph:order",
    ],
)

cc_test(
    name = "dataflow_test",
    srcs = ["dataflow_test.cc"],
    deps = [
        ":dataflow",
        "//lucid/core/container/graph:test_graph",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "worklist",
    hdrs = ["worklist.h"],
)

cc_test(
    name = "worklist_test",
    srcs = ["worklist_test.cc"],
    deps = [
        ":worklist",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "worklist_bench",
    srcs = ["worklist_bench.cc"],
    deps = [
        ":worklist",
        "@google_benchmark//:benchmark",
    ],
)
