load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "arena",
    hdrs = ["arena.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "arena_test",
    srcs = ["arena_test.cc"],
    deps = [
        ":arena",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "fixed_map",
    hdrs = ["fixed_map.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "fixed_map_test",
    srcs = ["fixed_map_test.cc"],
    deps = [
        ":fixed_map",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "hash_map",
    hdrs = ["hash_map.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":hash_table",
    ],
)

cc_test(
    name = "hash_map_test",
    srcs = ["hash_map_test.cc"],
    deps = [
        ":hash_map",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "hash_map_bench",
    srcs = ["hash_map_bench.cc"],
    deps = [
        ":hash_map",
        "//lucid/core/benchmarking",
    ],
)

cc_library(
    name = "hash_set",
    hdrs = ["hash_set.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":hash_table",
    ],
)

cc_test(
    name = "hash_set_test",
    srcs = ["hash_set_test.cc"],
    deps = [
        ":hash_set",
        "//lucid/core/testing",
    ],
)

cc_binary(
    name = "hash_set_bench",
    srcs = ["hash_set_bench.cc"],
    deps = [
        ":hash_set",
        "//lucid/core/benchmarking",
    ],
)

cc_library(
    name = "hash_table",
    hdrs = ["hash_table.h"],
    deps = [
        "//lucid/core/functional:identity",
        "//lucid/core/hash",
    ],
)

cc_library(
    name = "successive_list",
    hdrs = ["successive_list.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "successive_list_test",
    srcs = ["successive_list_test.cc"],
    deps = [
        ":successive_list",
        "//lucid/core/testing",
    ],
)
