load("@bazel_lib//lib:diff_test.bzl", "diff_test")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "testing_library",
    testonly = True,
    srcs = ["testing.cc"],
    hdrs = ["testing.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/meta:static_for",
        "//lucid/core/string:concat",
        "//lucid/core/testing/internal:boolean_matcher",
        "//lucid/core/testing/internal:equality_matcher",
        "//lucid/core/testing/internal:predicate_matcher",
    ],
    alwayslink = True,
)

cc_library(
    name = "testing",
    testonly = True,
    srcs = ["testing_main.cc"],
    hdrs = ["testing.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":testing_library",
        "//lucid/core/meta:static_for",
        "//lucid/core/string:concat",
        "//lucid/core/testing/internal:boolean_matcher",
        "//lucid/core/testing/internal:equality_matcher",
        "//lucid/core/testing/internal:predicate_matcher",
    ],
    alwayslink = True,
)

genrule(
    name = "run_passing_tests",
    testonly = True,
    outs = ["passing_tests_output"],
    cmd = "$(location //lucid/core/testing/testdata:passing_tests) --disable_timings > $@",
    tools = ["//lucid/core/testing/testdata:passing_tests"],
)

diff_test(
    name = "passing_tests_test",
    file1 = "//lucid/core/testing/testdata:expected_passing_tests_output",
    file2 = ":passing_tests_output",
)

genrule(
    name = "run_failing_tests",
    testonly = True,
    outs = ["failing_tests_output"],
    cmd = """
    if $(location //lucid/core/testing/testdata:failing_tests) --disable_timings > $@ 2>&1; then
      echo "ERROR: Expected tool to fail, but it exited with 0" >&2
      exit 1
    fi
    """,
    tools = ["//lucid/core/testing/testdata:failing_tests"],
)

diff_test(
    name = "failing_tests_test",
    file1 = "//lucid/core/testing/testdata:expected_failing_tests_output",
    file2 = ":failing_tests_output",
)
