load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//lucid/core/testing:__subpackages__"],
)

cc_library(
    name = "matcher",
    hdrs = ["matcher.h"],
)

cc_library(
    name = "all_matcher",
    hdrs = ["all_matcher.h"],
    deps = [
        ":matcher",
        "//lucid/core/meta:static_for",
        "//lucid/core/string:concat",
    ],
)

cc_library(
    name = "boolean_matcher",
    hdrs = ["boolean_matcher.h"],
)

cc_library(
    name = "elements_matcher",
    hdrs = ["elements_matcher.h"],
    deps = [
        ":matcher",
        ":to_string",
        "//lucid/core/meta:static_for",
        "//lucid/core/string:concat",
    ],
)

cc_library(
    name = "empty_matcher",
    hdrs = ["empty_matcher.h"],
)

cc_library(
    name = "equality_matcher",
    hdrs = ["equality_matcher.h"],
    deps = [":to_string"],
)

cc_library(
    name = "field_matcher",
    hdrs = ["field_matcher.h"],
    deps = [":matcher"],
)

cc_library(
    name = "not_matcher",
    hdrs = ["not_matcher.h"],
    deps = [":matcher"],
)

cc_library(
    name = "optional_matcher",
    hdrs = ["optional_matcher.h"],
    deps = [":matcher"],
)

cc_library(
    name = "pair_matcher",
    hdrs = ["pair_matcher.h"],
    deps = [":matcher"],
)

cc_library(
    name = "predicate_matcher",
    hdrs = ["predicate_matcher.h"],
)

cc_library(
    name = "prefix_matcher",
    hdrs = ["prefix_matcher.h"],
    deps = [":to_string"],
)

cc_library(
    name = "size_matcher",
    hdrs = ["size_matcher.h"],
    deps = [":matcher"],
)

cc_library(
    name = "suffix_matcher",
    hdrs = ["suffix_matcher.h"],
    deps = [":to_string"],
)

cc_library(
    name = "to_string",
    hdrs = ["to_string.h"],
)

cc_library(
    name = "unordered_elements_matcher",
    hdrs = ["unordered_elements_matcher.h"],
    deps = [
        ":matcher",
        ":to_string",
        "//lucid/core/meta:static_for",
        "//lucid/core/string:concat",
    ],
)

cc_library(
    name = "variant_matcher",
    hdrs = ["variant_matcher.h"],
    deps = [":matcher"],
)
