load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//lucid/core/testing:__subpackages__"],
)

cc_library(
    name = "boolean_matcher",
    hdrs = ["boolean_matcher.h"],
)

cc_library(
    name = "equality_matcher",
    hdrs = ["equality_matcher.h"],
)

cc_library(
    name = "predicate_matcher",
    hdrs = ["predicate_matcher.h"],
)
