load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "concat",
    srcs = ["concat.cc"],
    hdrs = ["concat.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "concat_test",
    srcs = ["concat_test.cc"],
    deps = [
        ":concat",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "encoding",
    srcs = ["encoding.cc"],
    hdrs = ["encoding.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "encoding_test",
    srcs = ["encoding_test.cc"],
    deps = [
        ":encoding",
        "//lucid/core/testing",
    ],
)

cc_library(
    name = "index",
    hdrs = ["index.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        "//lucid/core/container:hash_map",
        "//lucid/core/container:optional_ref",
    ],
)

cc_test(
    name = "index_test",
    srcs = ["index_test.cc"],
    deps = [
        ":index",
        "@googletest//:gtest_main",
    ],
)
