cc_library(
    name = "arena",
    hdrs = ["arena.h"],
)

cc_test(
    name = "arena_test",
    srcs = ["arena_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":arena",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "ast",
    hdrs = ["ast.h"],
    deps = [
        ":arena",
    ],
)

cc_library(
    name = "cpp_gen",
    srcs = ["cpp_gen.cc"],
    hdrs = ["cpp_gen.h"],
    deps = [
        ":arena",
        ":ast",
    ],
)

cc_test(
    name = "cpp_gen_test",
    srcs = ["cpp_gen_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":arena",
        ":ast",
        ":cpp_gen",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
