load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_binary(
    name = "compiler",
    srcs = ["compiler.cc"],
    deps = [
        ":opt",
        ":reg",
        ":static",
        ":type",
        ":version",
        "//lucid/am:cfg",
        "//lucid/am:cfg_printer",
        "//lucid/am:translator",
        "//lucid/arm64:assembler",
        "//lucid/arm64:macho",
        "//lucid/arm64:translator",
        "//lucid/core/cli",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/io:file",
        "//lucid/syntax:ast",
        "//lucid/syntax:ast_printer",
        "//lucid/syntax:buffered_lexer",
        "//lucid/syntax:cfg",
        "//lucid/syntax:cfg_printer",
        "//lucid/syntax:lexer",
        "//lucid/syntax:parser",
        "//lucid/syntax:ssa",
    ],
)

cc_test(
    name = "compiler_test",
    srcs = ["compiler_test.cc"],
    data = [
        ":compiler",
    ],
    deps = [
        ":compiler_test_fixture",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "compiler_macos_arm64_test",
    srcs = ["compiler_macos_arm64_test.cc"],
    data = [
        ":compiler",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
    deps = [
        ":compiler_test_fixture",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "compiler_test_fixture",
    testonly = True,
    hdrs = ["compiler_test_fixture.h"],
    deps = [
        "//lucid/core/io:file",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "opt",
    srcs = ["opt.cc"],
    hdrs = ["opt.h"],
    deps = [
        "//lucid/am:instructions",
    ],
)

cc_test(
    name = "opt_test",
    srcs = ["opt_test.cc"],
    deps = [
        ":opt",
        "//lucid/am:instructions",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "reg",
    srcs = ["reg.cc"],
    hdrs = ["reg.h"],
    deps = [
        "//lucid/am:cfg",
        "//lucid/am:liveness",
        "//lucid/core/container:hash_map",
        "//lucid/core/container:hash_set",
        "//lucid/core/container/graph:dominator",
        "//lucid/core/dataflow",
    ],
)

cc_test(
    name = "reg_test",
    srcs = ["reg_test.cc"],
    deps = [
        ":reg",
        "//lucid/am:cfg",
        "//lucid/syntax:ast",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "static",
    srcs = ["static.cc"],
    hdrs = ["static.h"],
    deps = [
        "//lucid/core/functional:result",
        "//lucid/syntax:ast",
        "//lucid/syntax:cfg",
    ],
)

cc_test(
    name = "static_test",
    srcs = ["static_test.cc"],
    deps = [
        ":static",
        "//lucid/syntax:ast",
        "//lucid/syntax:ast_fixture",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "type",
    srcs = ["type.cc"],
    hdrs = ["type.h"],
    visibility = ["//lucid/am:__subpackages__"],
    deps = [
        "//lucid/core/functional:result",
        "//lucid/core/string:index",
        "//lucid/syntax:ast",
    ],
)

cc_test(
    name = "type_test",
    srcs = ["type_test.cc"],
    deps = [
        ":type",
        "//lucid/core/functional:result",
        "//lucid/syntax:ast",
        "//lucid/syntax:ast_fixture",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "version",
    hdrs = ["version.h"],
)

genrule(
    name = "version_gen",
    srcs = ["version.h.tmpl"],
    outs = ["version.h"],
    cmd_bash = """
      commit=$$(grep ^STABLE_GIT_COMMIT bazel-out/stable-status.txt | cut -d ' ' -f2 ||
                echo "unstamped"); \
      sed -e 's/%GIT_COMMIT%/'$$commit'/' < $< > $@
    """,
    stamp = 1,
)
