cc_library(
    name = "am",
    hdrs = ["am.h"],
)

cc_library(
    name = "am_gen",
    srcs = ["am_gen.cc"],
    hdrs = ["am_gen.h"],
    deps = [
        ":am",
        ":arena",
        ":ast",
        ":cfg",
    ],
)

cc_test(
    name = "am_gen_test",
    srcs = ["am_gen_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":am",
        ":am_gen",
        ":arena",
        ":cfg",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "arena",
    hdrs = ["arena.h"],
)

cc_test(
    name = "arena_test",
    srcs = ["arena_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":arena",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "arm64_compiler_test",
    srcs = ["arm64_compiler_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    data = [
        ":compiler",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
        "@platforms//cpu:arm",
    ],
    deps = [
        ":cli",
        ":file",
        ":test_cli",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "arm64_gen",
    srcs = ["arm64_gen.cc"],
    hdrs = ["arm64_gen.h"],
    deps = [
        ":am",
        ":am_gen",
    ],
)

cc_test(
    name = "arm64_gen_test",
    srcs = ["arm64_gen_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":am_gen",
        ":arena",
        ":arm64_gen",
        ":ast",
        ":cfg",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "ast",
    hdrs = ["ast.h"],
    deps = [
        ":arena",
    ],
)

cc_library(
    name = "cfg",
    srcs = ["cfg.cc"],
    hdrs = ["cfg.h"],
    deps = [
        ":arena",
        ":ast",
    ],
)

cc_test(
    name = "cfg_test",
    srcs = ["cfg_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":arena",
        ":ast",
        ":cfg",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "cli",
    srcs = ["cli.cc"],
    hdrs = ["cli.h"],
)

cc_test(
    name = "cli_test",
    srcs = ["cli_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":cli",
        ":test_cli",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_binary(
    name = "compiler",
    srcs = ["compiler.cc"],
    deps = [
        ":am_gen",
        ":arena",
        ":arm64_gen",
        ":ast",
        ":cfg",
        ":cli",
        ":file",
        ":lexer",
        ":opt",
        ":parser",
        ":version",
    ],
)

cc_library(
    name = "file",
    srcs = ["file.cc"],
    hdrs = ["file.h"],
)

cc_test(
    name = "file_test",
    srcs = ["file_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    data = [
        "//lucid/testdata:foobarbaz",
    ],
    deps = [
        ":file",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "lexer",
    hdrs = ["lexer.h"],
    deps = [
        ":token",
    ],
)

cc_test(
    name = "lexer_test",
    srcs = ["lexer_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":lexer",
        ":token",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "opt",
    srcs = ["opt.cc"],
    hdrs = ["opt.h"],
    deps = [
        ":am",
    ],
)

cc_test(
    name = "opt_test",
    srcs = ["opt_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":am",
        ":opt",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "parser",
    hdrs = ["parser.h"],
    deps = [
        ":arena",
        ":ast",
        ":lexer",
        ":token",
    ],
)

cc_test(
    name = "parser_test",
    srcs = ["parser_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":arena",
        ":ast",
        ":lexer",
        ":parser",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "test_cli",
    testonly = True,
    hdrs = ["test_cli.h"],
    deps = [
        "@gtest",
    ],
)

cc_library(
    name = "token",
    srcs = ["token.cc"],
    hdrs = ["token.h"],
)

cc_test(
    name = "token_test",
    srcs = ["token_test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        ":token",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "version",
    hdrs = ["version.h"],
)

genrule(
    name = "version_gen",
    srcs = ["version.h.tmpl"],
    outs = ["version.h"],
    cmd_bash = """
      commit=$$(grep ^STABLE_GIT_COMMIT bazel-out/stable-status.txt | cut -d ' ' -f2 ||
                echo "unstamped"); \
      sed -e 's/%GIT_COMMIT%/'$$commit'/' < $< > $@
    """,
    stamp = 1,
)
