load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "expected",
    hdrs = ["expected.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = ["//lucid/core/meta:macros"],
)

cc_library(
    name = "identity",
    hdrs = ["identity.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "identity_test",
    srcs = ["identity_test.cc"],
    deps = [
        ":identity",
        "//lucid/core/testing",
    ],
)
