name: lucid

on: [push]

jobs:
  test:
    runs-on: xcode-27
    steps:
      - uses: actions/checkout@v7
      - name: Use the Command Line Tools toolchain
        run: sudo xcode-select -s /Library/Developer/CommandLineTools
      - name: Run tests
        run: bazel test ...
      - name: Run tests in opt mode
        run: bazel test -c opt ...
      - name: Run tests in ASan mode
        run: bazel test --config=asan ...
      - name: Run tests in UBSan mode
        run: bazel test --config=ubsan ...
      - name: Run benchmarks
        run: |
          bazel run -c opt //lucid/syntax:lexer_bench
          bazel run -c opt //lucid/syntax:parser_bench
          bazel run -c opt //lucid/core/container:hash_map_bench
          bazel run -c opt //lucid/core/container:hash_set_bench
          bazel run -c opt //lucid/syntax:ssa_bench
          bazel run -c opt //lucid/am:reg_bench
          bazel run -c opt //lucid/core/dataflow:worklist_bench
