name: lucid

on: [push]

jobs:
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: bazel test ...
      - name: Run tests in opt mode
        run: bazel test -c opt ...
      - name: Run tests in ASan mode
        run: bazel test --config=asan ...
      - name: Run tests in UBSan mode
        run: bazel test --config=ubsan ...
      - name: Run benchmarks
        run: |
          bazel run -c opt //lucid:lexer_bench
          bazel run -c opt //lucid:parser_bench
