name: lucid

on: [push]

jobs:
  test:
    runs-on: macos-14-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.3.app/Contents/Developer'
      - name: Run tests
        run: |
          bazel test ...
          bazel test -c opt ...
      - name: Run benchmarks
        run: |
          bazel run -c opt //lucid:lexer_bench
          bazel run -c opt //lucid:parser_bench
