load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "cli",
    srcs = ["cli.cc"],
    hdrs = ["cli.h"],
    visibility = ["//lucid:__subpackages__"],
    deps = [
        ":format",
        "//lucid/core/container:hash_map",
        "//lucid/core/string:concat",
    ],
)

cc_test(
    name = "cli_test",
    srcs = ["cli_test.cc"],
    deps = [
        ":cli",
        "//lucid/core/container:hash_map",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "format",
    hdrs = ["format.h"],
    visibility = ["//lucid:__subpackages__"],
)

cc_test(
    name = "format_test",
    srcs = ["format_test.cc"],
    deps = [
        ":format",
        "//lucid/core/testing",
    ],
)
